const VOCABULARY = {
  hsk1: [
    { zh: "你好", py: "nǐ hǎo", th: "สวัสดี", type: "greeting" },
    { zh: "谢谢", py: "xiè xie", th: "ขอบคุณ", type: "greeting" },
    { zh: "不客气", py: "bú kè qi", th: "ไม่เป็นไร", type: "greeting" },
    { zh: "对不起", py: "duì bu qǐ", th: "ขอโทษ", type: "greeting" },
    { zh: "没关系", py: "méi guān xi", th: "ไม่เป็นไร", type: "greeting" },
    { zh: "再见", py: "zài jiàn", th: "ลาก่อน", type: "greeting" },
    { zh: "请", py: "qǐng", th: "กรุณา", type: "greeting" },
    { zh: "是", py: "shì", th: "เป็น", type: "copula" },
    { zh: "不是", py: "bú shì", th: "ไม่ใช่", type: "copula" },
    { zh: "有", py: "yǒu", th: "มี", type: "copula" },
    { zh: "没有", py: "méi yǒu", th: "ไม่มี", type: "copula" },

    { zh: "我", py: "wǒ", th: "ฉัน", type: "pronoun" },
    { zh: "你", py: "nǐ", th: "คุณ", type: "pronoun" },
    { zh: "他", py: "tā", th: "เขา", type: "pronoun" },
    { zh: "她", py: "tā", th: "เธอ", type: "pronoun" },
    { zh: "我们", py: "wǒ men", th: "พวกเรา", type: "pronoun" },
    { zh: "你们", py: "nǐ men", th: "พวกคุณ", type: "pronoun" },
    { zh: "他们", py: "tā men", th: "พวกเขา", type: "pronoun" },

    { zh: "老师", py: "lǎo shī", th: "ครู", type: "noun" },
    { zh: "学生", py: "xué sheng", th: "นักเรียน", type: "noun" },
    { zh: "朋友", py: "péng you", th: "เพื่อน", type: "noun" },
    { zh: "医生", py: "yī shēng", th: "หมอ", type: "noun" },
    { zh: "同学", py: "tóng xué", th: "เพื่อนร่วมชั้น", type: "noun" },

    { zh: "中国", py: "zhōng guó", th: "ประเทศจีน", type: "noun" },
    { zh: "学校", py: "xué xiào", th: "โรงเรียน", type: "noun" },
    { zh: "家", py: "jiā", th: "บ้าน", type: "noun" },
    { zh: "商店", py: "shāng diàn", th: "ร้านค้า", type: "noun" },
    { zh: "医院", py: "yī yuàn", th: "โรงพยาบาล", type: "noun" },

    { zh: "爸爸", py: "bà ba", th: "พ่อ", type: "noun" },
    { zh: "妈妈", py: "mā ma", th: "แม่", type: "noun" },
    { zh: "哥哥", py: "gē ge", th: "พี่ชาย", type: "noun" },
    { zh: "姐姐", py: "jiě jie", th: "พี่สาว", type: "noun" },
    { zh: "弟弟", py: "dì di", th: "น้องชาย", type: "noun" },
    { zh: "妹妹", py: "mèi mei", th: "น้องสาว", type: "noun" },

    { zh: "水", py: "shuǐ", th: "น้ำ", type: "noun" },
    { zh: "茶", py: "chá", th: "ชา", type: "noun" },
    { zh: "咖啡", py: "kā fēi", th: "กาแฟ", type: "noun" },
    { zh: "牛奶", py: "niú nǎi", th: "นม", type: "noun" },
    { zh: "米饭", py: "mǐ fàn", th: "ข้าว", type: "noun" },
    { zh: "苹果", py: "píng guǒ", th: "แอปเปิล", type: "noun" },
    { zh: "菜", py: "cài", th: "อาหาร", type: "noun" },
    { zh: "水果", py: "shuǐ guǒ", th: "ผลไม้", type: "noun" },

    { zh: "猫", py: "māo", th: "แมว", type: "noun" },
    { zh: "狗", py: "gǒu", th: "สุนัข", type: "noun" },

    { zh: "一", py: "yī", th: "หนึ่ง", type: "number" },
    { zh: "二", py: "èr", th: "สอง", type: "number" },
    { zh: "三", py: "sān", th: "สาม", type: "number" },
    { zh: "四", py: "sì", th: "สี่", type: "number" },
    { zh: "五", py: "wǔ", th: "ห้า", type: "number" },
    { zh: "六", py: "liù", th: "หก", type: "number" },
    { zh: "七", py: "qī", th: "เจ็ด", type: "number" },
    { zh: "八", py: "bā", th: "แปด", type: "number" },
    { zh: "九", py: "jiǔ", th: "เก้า", type: "number" },
    { zh: "十", py: "shí", th: "สิบ", type: "number" },

    { zh: "今天", py: "jīn tiān", th: "วันนี้", type: "time" },
    { zh: "明天", py: "míng tiān", th: "พรุ่งนี้", type: "time" },
    { zh: "昨天", py: "zuó tiān", th: "เมื่อวาน", type: "time" },
    { zh: "上午", py: "shàng wǔ", th: "ตอนเช้า", type: "time" },
    { zh: "下午", py: "xià wǔ", th: "ตอนบ่าย", type: "time" },
    { zh: "晚上", py: "wǎn shang", th: "ตอนเย็น", type: "time" },
    { zh: "现在", py: "xiàn zài", th: "ตอนนี้", type: "time" },

    { zh: "星期一", py: "xīng qī yī", th: "วันจันทร์", type: "time" },
    { zh: "星期二", py: "xīng qī èr", th: "วันอังคาร", type: "time" },
    { zh: "星期三", py: "xīng qī sān", th: "วันพุธ", type: "time" },
    { zh: "星期四", py: "xīng qī sì", th: "วันพฤหัส", type: "time" },
    { zh: "星期五", py: "xīng qī wǔ", th: "วันศุกร์", type: "time" },
    { zh: "星期六", py: "xīng qī liù", th: "วันเสาร์", type: "time" },
    { zh: "星期天", py: "xīng qī tiān", th: "วันอาทิตย์", type: "time" },

    { zh: "大", py: "dà", th: "ใหญ่", type: "adj" },
    { zh: "小", py: "xiǎo", th: "เล็ก", type: "adj" },
    { zh: "多", py: "duō", th: "มาก", type: "adj" },
    { zh: "少", py: "shǎo", th: "น้อย", type: "adj" },
    { zh: "好", py: "hǎo", th: "ดี", type: "adj" },
    { zh: "热", py: "rè", th: "ร้อน", type: "adj" },
    { zh: "冷", py: "lěng", th: "หนาว", type: "adj" },

    { zh: "吃", py: "chī", th: "กิน", type: "verb" },
    { zh: "喝", py: "hē", th: "ดื่ม", type: "verb" },
    { zh: "看", py: "kàn", th: "ดู", type: "verb" },
    { zh: "听", py: "tīng", th: "ฟัง", type: "verb" },
    { zh: "说", py: "shuō", th: "พูด", type: "verb" },
    { zh: "读", py: "dú", th: "อ่าน", type: "verb" },
    { zh: "写", py: "xiě", th: "เขียน", type: "verb" },
    { zh: "买", py: "mǎi", th: "ซื้อ", type: "verb" },
    { zh: "去", py: "qù", th: "ไป", type: "verb" },
    { zh: "来", py: "lái", th: "มา", type: "verb" },
    { zh: "回", py: "huí", th: "กลับ", type: "verb" },
    { zh: "学习", py: "xué xí", th: "เรียน", type: "verb" },

    { zh: "什么", py: "shén me", th: "อะไร", type: "question", sentence: "你在做___？" },
    { zh: "谁", py: "shéi", th: "ใคร", type: "question", sentence: "___是你的老师？" },
    { zh: "哪", py: "nǎ", th: "ไหน", type: "question", sentence: "你是___国人？" },
    { zh: "怎么", py: "zěn me", th: "อย่างไร", type: "question", sentence: "你___去学校？" },
    { zh: "为什么", py: "wèi shén me", th: "ทำไม", type: "question", sentence: "___你不来？" },
    { zh: "多少", py: "duō shǎo", th: "เท่าไร", type: "question", sentence: "这个___钱？" },
    { zh: "几", py: "jǐ", th: "กี่", type: "question", sentence: "现在___点？" },
  ],

  hsk2: [
    { zh: "认识", py: "rèn shi", th: "รู้จัก", type: "verb" },
    { zh: "准备", py: "zhǔn bèi", th: "เตรียม", type: "verb" },
    { zh: "觉得", py: "jué de", th: "คิดว่า", type: "verb" },
    { zh: "帮助", py: "bāng zhù", th: "ช่วยเหลือ", type: "verb" },
    { zh: "开始", py: "kāi shǐ", th: "เริ่ม", type: "verb" },
    { zh: "结束", py: "jié shù", th: "จบ", type: "verb" },
    { zh: "学习", py: "xué xí", th: "เรียน", type: "verb" },
    { zh: "工作", py: "gōng zuò", th: "ทำงาน", type: "verb" },
    { zh: "运动", py: "yùn dòng", th: "ออกกำลังกาย", type: "verb" },
    { zh: "时间", py: "shí jiān", th: "เวลา", type: "noun" },

    { zh: "重要", py: "zhòng yào", th: "สำคัญ", type: "adj" },
    { zh: "容易", py: "róng yì", th: "ง่าย", type: "adj" },
    { zh: "困难", py: "kùn nan", th: "ยาก", type: "adj" },
    { zh: "明白", py: "míng bai", th: "เข้าใจ", type: "verb" },
    { zh: "完成", py: "wán chéng", th: "ทำเสร็จ", type: "verb" },
    { zh: "一起", py: "yì qǐ", th: "ด้วยกัน", type: "verb", sentence: "我们___去公园，好吗？" },
    { zh: "附近", py: "fù jìn", th: "ใกล้", type: "direction" },
    { zh: "旅游", py: "lǚ yóu", th: "ท่องเที่ยว", type: "verb" },
    { zh: "放心", py: "fàng xīn", th: "วางใจ", type: "verb" },
    { zh: "希望", py: "xī wàng", th: "หวัง", type: "verb" },

    { zh: "告诉", py: "gào su", th: "บอก", type: "verb" },
    { zh: "回答", py: "huí dá", th: "ตอบ", type: "verb" },
    { zh: "问题", py: "wèn tí", th: "คำถาม", type: "noun" },
    { zh: "知道", py: "zhī dao", th: "รู้", type: "verb" },
    { zh: "比较", py: "bǐ jiào", th: "เปรียบเทียบ", type: "verb" },
    { zh: "欢迎", py: "huān yíng", th: "ยินดีต้อนรับ", type: "verb" },
    { zh: "介绍", py: "jiè shào", th: "แนะนำ", type: "verb" },
    { zh: "唱歌", py: "chàng gē", th: "ร้องเพลง", type: "verb" },
    { zh: "跳舞", py: "tiào wǔ", th: "เต้น", type: "verb" },
    { zh: "考试", py: "kǎo shì", th: "สอบ", type: "noun" },

    { zh: "公司", py: "gōng sī", th: "บริษัท", type: "noun" },
    { zh: "办公室", py: "bàn gōng shì", th: "สำนักงาน", type: "noun" },
    { zh: "手机", py: "shǒu jī", th: "โทรศัพท์มือถือ", type: "noun" },
    { zh: "电脑", py: "diàn nǎo", th: "คอมพิวเตอร์", type: "noun" },
    { zh: "电影", py: "diàn yǐng", th: "ภาพยนตร์", type: "noun" },
    { zh: "电视", py: "diàn shì", th: "โทรทัศน์", type: "noun" },
    { zh: "节目", py: "jié mù", th: "รายการ", type: "noun" },
    { zh: "新闻", py: "xīn wén", th: "ข่าว", type: "noun" },
    { zh: "照片", py: "zhào piàn", th: "รูปภาพ", type: "noun" },
    { zh: "颜色", py: "yán sè", th: "สี", type: "noun" },

    { zh: "红色", py: "hóng sè", th: "สีแดง", type: "noun" },
    { zh: "蓝色", py: "lán sè", th: "สีน้ำเงิน", type: "noun" },
    { zh: "白色", py: "bái sè", th: "สีขาว", type: "noun" },
    { zh: "黑色", py: "hēi sè", th: "สีดำ", type: "noun" },
    { zh: "绿色", py: "lǜ sè", th: "สีเขียว", type: "noun" },

    { zh: "便宜", py: "pián yi", th: "ราคาถูก", type: "adj" },
    { zh: "贵", py: "guì", th: "แพง", type: "adj" },
    { zh: "长", py: "cháng", th: "ยาว", type: "adj" },
    { zh: "短", py: "duǎn", th: "สั้น", type: "adj" },
    { zh: "高", py: "gāo", th: "สูง", type: "adj" },
    { zh: "低", py: "dī", th: "ต่ำ", type: "adj" },
    { zh: "胖", py: "pàng", th: "อ้วน", type: "adj" },
    { zh: "瘦", py: "shòu", th: "ผอม", type: "adj" },

    { zh: "笑", py: "xiào", th: "หัวเราะ", type: "verb" },
    { zh: "哭", py: "kū", th: "ร้องไห้", type: "verb" },
    { zh: "走", py: "zǒu", th: "เดิน", type: "verb" },
    { zh: "跑", py: "pǎo", th: "วิ่ง", type: "verb" },
    { zh: "打开", py: "dǎ kāi", th: "เปิด", type: "verb" },
    { zh: "关上", py: "guān shàng", th: "ปิด", type: "verb" },
    { zh: "起床", py: "qǐ chuáng", th: "ตื่นนอน", type: "verb" },
    { zh: "睡觉", py: "shuì jiào", th: "นอน", type: "verb" },
    { zh: "洗澡", py: "xǐ zǎo", th: "อาบน้ำ", type: "verb" },
    { zh: "洗手", py: "xǐ shǒu", th: "ล้างมือ", type: "verb" },

    { zh: "天气", py: "tiān qì", th: "อากาศ", type: "noun" },
    { zh: "下雨", py: "xià yǔ", th: "ฝนตก", type: "verb" },
    { zh: "下雪", py: "xià xuě", th: "หิมะตก", type: "verb" },
    { zh: "风", py: "fēng", th: "ลม", type: "noun" },
    { zh: "太阳", py: "tài yáng", th: "พระอาทิตย์", type: "noun" },

    { zh: "左边", py: "zuǒ biān", th: "ด้านซ้าย", type: "direction" },
    { zh: "右边", py: "yòu biān", th: "ด้านขวา", type: "direction" },
    { zh: "前面", py: "qián miàn", th: "ด้านหน้า", type: "direction" },
    { zh: "后面", py: "hòu miàn", th: "ด้านหลัง", type: "direction" },
    { zh: "里面", py: "lǐ miàn", th: "ข้างใน", type: "direction" },
    { zh: "外面", py: "wài miàn", th: "ข้างนอก", type: "direction" },
  ],

  hsk3: [
    { zh: "打算", py: "dǎ suàn", th: "วางแผน", type: "verb" },
    { zh: "提高", py: "tí gāo", th: "พัฒนา", type: "verb" },
    { zh: "适应", py: "shì yìng", th: "ปรับตัว", type: "verb" },
    { zh: "经验", py: "jīng yàn", th: "ประสบการณ์", type: "noun" },
    { zh: "成功", py: "chéng gōng", th: "สำเร็จ", type: "verb" },
    { zh: "失败", py: "shī bài", th: "ล้มเหลว", type: "verb" },
    { zh: "决定", py: "jué dìng", th: "ตัดสินใจ", type: "verb" },
    { zh: "建议", py: "jiàn yì", th: "เสนอ", type: "verb" },
    { zh: "检查", py: "jiǎn chá", th: "ตรวจสอบ", type: "verb" },
    { zh: "保持", py: "bǎo chí", th: "รักษา", type: "verb" },

    { zh: "改变", py: "gǎi biàn", th: "เปลี่ยน", type: "verb" },
    { zh: "继续", py: "jì xù", th: "ต่อเนื่อง", type: "verb" },
    { zh: "交流", py: "jiāo liú", th: "แลกเปลี่ยน", type: "verb" },
    { zh: "理解", py: "lǐ jiě", th: "เข้าใจ", type: "verb" },
    { zh: "联系", py: "lián xì", th: "ติดต่อ", type: "verb" },
    { zh: "努力", py: "nǔ lì", th: "พยายาม", type: "verb" },
    { zh: "选择", py: "xuǎn zé", th: "เลือก", type: "verb" },
    { zh: "习惯", py: "xí guàn", th: "เคยชิน", type: "noun" },
    { zh: "负责", py: "fù zé", th: "รับผิดชอบ", type: "verb" },
    { zh: "机会", py: "jī huì", th: "โอกาส", type: "noun" },

    { zh: "发现", py: "fā xiàn", th: "ค้นพบ", type: "verb" },
    { zh: "参加", py: "cān jiā", th: "เข้าร่วม", type: "verb" },
    { zh: "讨论", py: "tǎo lùn", th: "อภิปราย", type: "verb" },
    { zh: "解释", py: "jiě shì", th: "อธิบาย", type: "verb" },
    { zh: "计划", py: "jì huà", th: "แผน", type: "noun" },
    { zh: "保护", py: "bǎo hù", th: "ปกป้อง", type: "verb" },
    { zh: "帮助", py: "bāng zhù", th: "ช่วยเหลือ", type: "verb" },
    { zh: "完成", py: "wán chéng", th: "ทำสำเร็จ", type: "verb" },
    { zh: "比较", py: "bǐ jiào", th: "เปรียบเทียบ", type: "verb" },
    { zh: "发展", py: "fā zhǎn", th: "พัฒนา", type: "verb" },

    { zh: "环境", py: "huán jìng", th: "สิ่งแวดล้อม", type: "noun" },
    { zh: "社会", py: "shè huì", th: "สังคม", type: "noun" },
    { zh: "文化", py: "wén huà", th: "วัฒนธรรม", type: "noun" },
    { zh: "教育", py: "jiào yù", th: "การศึกษา", type: "noun" },
    { zh: "经济", py: "jīng jì", th: "เศรษฐกิจ", type: "noun" },
    { zh: "历史", py: "lì shǐ", th: "ประวัติศาสตร์", type: "noun" },
    { zh: "科学", py: "kē xué", th: "วิทยาศาสตร์", type: "noun" },
    { zh: "技术", py: "jì shù", th: "เทคโนโลยี", type: "noun" },
    { zh: "知识", py: "zhī shi", th: "ความรู้", type: "noun" },
    { zh: "能力", py: "néng lì", th: "ความสามารถ", type: "noun" },

    { zh: "影响", py: "yǐng xiǎng", th: "ผลกระทบ", type: "verb" },
    { zh: "原因", py: "yuán yīn", th: "สาเหตุ", type: "noun" },
    { zh: "结果", py: "jié guǒ", th: "ผลลัพธ์", type: "noun" },
    { zh: "过程", py: "guò chéng", th: "กระบวนการ", type: "noun" },
    { zh: "目标", py: "mù biāo", th: "เป้าหมาย", type: "noun" },
    { zh: "内容", py: "nèi róng", th: "เนื้อหา", type: "noun" },
    { zh: "情况", py: "qíng kuàng", th: "สถานการณ์", type: "noun" },
    { zh: "方法", py: "fāng fǎ", th: "วิธีการ", type: "noun" },
    { zh: "标准", py: "biāo zhǔn", th: "มาตรฐาน", type: "noun" },
    { zh: "态度", py: "tài dù", th: "ทัศนคติ", type: "noun" },

    { zh: "健康", py: "jiàn kāng", th: "สุขภาพ", type: "adj" },
    { zh: "安全", py: "ān quán", th: "ปลอดภัย", type: "adj" },
    { zh: "紧张", py: "jǐn zhāng", th: "ตื่นเต้น", type: "adj" },
    { zh: "轻松", py: "qīng sōng", th: "ผ่อนคลาย", type: "adj" },
    { zh: "开心", py: "kāi xīn", th: "มีความสุข", type: "adj" },
    { zh: "伤心", py: "shāng xīn", th: "เสียใจ", type: "adj" },
    { zh: "勇敢", py: "yǒng gǎn", th: "กล้าหาญ", type: "adj" },
    { zh: "认真", py: "rèn zhēn", th: "จริงจัง", type: "adj" },
    { zh: "耐心", py: "nài xīn", th: "อดทน", type: "adj" },
    { zh: "诚实", py: "chéng shí", th: "ซื่อสัตย์", type: "adj" },

    { zh: "城市", py: "chéng shì", th: "เมือง", type: "noun" },
    { zh: "农村", py: "nóng cūn", th: "ชนบท", type: "noun" },
    { zh: "交通", py: "jiāo tōng", th: "การคมนาคม", type: "noun" },
    { zh: "地图", py: "dì tú", th: "แผนที่", type: "noun" },
    { zh: "机场", py: "jī chǎng", th: "สนามบิน", type: "noun" },
    { zh: "火车站", py: "huǒ chē zhàn", th: "สถานีรถไฟ", type: "noun" },
    { zh: "银行", py: "yín háng", th: "ธนาคาร", type: "noun" },
    { zh: "超市", py: "chāo shì", th: "ซูเปอร์มาร์เก็ต", type: "noun" },
    { zh: "市场", py: "shì chǎng", th: "ตลาด", type: "noun" },
    { zh: "餐厅", py: "cān tīng", th: "ร้านอาหาร", type: "noun" },
  ],

  hsk4: [
    { zh: "经历", py: "jīng lì", th: "ประสบการณ์", type: "noun" },
    { zh: "合作", py: "hé zuò", th: "ร่วมมือ", type: "verb" },
    { zh: "调整", py: "tiáo zhěng", th: "ปรับเปลี่ยน", type: "verb" },
    { zh: "出色", py: "chū sè", th: "โดดเด่น", type: "adj" },
    { zh: "管理", py: "guǎn lǐ", th: "บริหาร", type: "verb" },
    { zh: "影响", py: "yǐng xiǎng", th: "ส่งผล", type: "verb" },
    { zh: "责任", py: "zé rèn", th: "ความรับผิดชอบ", type: "noun" },
    { zh: "条件", py: "tiáo jiàn", th: "เงื่อนไข", type: "noun" },
    { zh: "目的", py: "mù dì", th: "จุดประสงค์", type: "noun" },
    { zh: "过程", py: "guò chéng", th: "กระบวนการ", type: "noun" },

    { zh: "表达", py: "biǎo dá", th: "แสดงออก", type: "verb" },
    { zh: "控制", py: "kòng zhì", th: "ควบคุม", type: "verb" },
    { zh: "调查", py: "diào chá", th: "สำรวจ", type: "verb" },
    { zh: "解决", py: "jiě jué", th: "แก้ไข", type: "verb" },
    { zh: "判断", py: "pàn duàn", th: "ตัดสิน", type: "verb" },
    { zh: "安排", py: "ān pái", th: "จัดการ", type: "verb" },
    { zh: "组织", py: "zǔ zhī", th: "องค์กร", type: "verb" },
    { zh: "说明", py: "shuō míng", th: "อธิบาย", type: "verb" },
    { zh: "结果", py: "jié guǒ", th: "ผลลัพธ์", type: "noun" },
    { zh: "接受", py: "jiē shòu", th: "ยอมรับ", type: "verb" },

    { zh: "拒绝", py: "jù jué", th: "ปฏิเสธ", type: "verb" },
    { zh: "减少", py: "jiǎn shǎo", th: "ลดลง", type: "verb" },
    { zh: "增加", py: "zēng jiā", th: "เพิ่มขึ้น", type: "verb" },
    { zh: "保持", py: "bǎo chí", th: "รักษา", type: "verb" },
    { zh: "完成", py: "wán chéng", th: "ทำสำเร็จ", type: "verb" },
    { zh: "提供", py: "tí gōng", th: "จัดหา", type: "verb" },
    { zh: "创造", py: "chuàng zào", th: "สร้าง", type: "verb" },
    { zh: "发展", py: "fā zhǎn", th: "พัฒนา", type: "verb" },
    { zh: "改善", py: "gǎi shàn", th: "ปรับปรุง", type: "verb" },
    { zh: "适合", py: "shì hé", th: "เหมาะสม", type: "verb" },

    { zh: "复杂", py: "fù zá", th: "ซับซ้อน", type: "adj" },
    { zh: "简单", py: "jiǎn dān", th: "ง่าย", type: "adj" },
    { zh: "明显", py: "míng xiǎn", th: "ชัดเจน", type: "adj" },
    { zh: "丰富", py: "fēng fù", th: "อุดมสมบูรณ์", type: "adj" },
    { zh: "积极", py: "jī jí", th: "เชิงบวก", type: "adj" },
    { zh: "消极", py: "xiāo jí", th: "เชิงลบ", type: "adj" },
    { zh: "严重", py: "yán zhòng", th: "รุนแรง", type: "adj" },
    { zh: "普通", py: "pǔ tōng", th: "ทั่วไป", type: "adj" },
    { zh: "重要", py: "zhòng yào", th: "สำคัญ", type: "adj" },
    { zh: "合理", py: "hé lǐ", th: "สมเหตุสมผล", type: "adj" },

    { zh: "环境", py: "huán jìng", th: "สิ่งแวดล้อม", type: "noun" },
    { zh: "社会", py: "shè huì", th: "สังคม", type: "noun" },
    { zh: "文化", py: "wén huà", th: "วัฒนธรรม", type: "noun" },
    { zh: "教育", py: "jiào yù", th: "การศึกษา", type: "noun" },
    { zh: "经济", py: "jīng jì", th: "เศรษฐกิจ", type: "noun" },
    { zh: "技术", py: "jì shù", th: "เทคโนโลยี", type: "noun" },
    { zh: "资源", py: "zī yuán", th: "ทรัพยากร", type: "noun" },
    { zh: "机会", py: "jī huì", th: "โอกาส", type: "noun" },
    { zh: "标准", py: "biāo zhǔn", th: "มาตรฐาน", type: "noun" },
    { zh: "质量", py: "zhì liàng", th: "คุณภาพ", type: "noun" },

    { zh: "会议", py: "huì yì", th: "การประชุม", type: "noun" },
    { zh: "项目", py: "xiàng mù", th: "โครงการ", type: "noun" },
    { zh: "计划", py: "jì huà", th: "แผน", type: "noun" },
    { zh: "报告", py: "bào gào", th: "รายงาน", type: "noun" },
    { zh: "任务", py: "rèn wu", th: "ภารกิจ", type: "noun" },
    { zh: "资料", py: "zī liào", th: "ข้อมูล", type: "noun" },
    { zh: "经验", py: "jīng yàn", th: "ประสบการณ์", type: "noun" },
    { zh: "能力", py: "néng lì", th: "ความสามารถ", type: "noun" },
    { zh: "知识", py: "zhī shi", th: "ความรู้", type: "noun" },
    { zh: "水平", py: "shuǐ píng", th: "ระดับ", type: "noun" },

    { zh: "联系", py: "lián xì", th: "ติดต่อ", type: "verb" },
    { zh: "交流", py: "jiāo liú", th: "แลกเปลี่ยน", type: "verb" },
    { zh: "讨论", py: "tǎo lùn", th: "อภิปราย", type: "verb" },
    { zh: "分析", py: "fēn xī", th: "วิเคราะห์", type: "verb" },
    { zh: "比较", py: "bǐ jiào", th: "เปรียบเทียบ", type: "verb" },
    { zh: "观察", py: "guān chá", th: "สังเกต", type: "verb" },
    { zh: "研究", py: "yán jiū", th: "วิจัย", type: "verb" },
    { zh: "理解", py: "lǐ jiě", th: "เข้าใจ", type: "verb" },
    { zh: "信任", py: "xìn rèn", th: "เชื่อใจ", type: "verb" },
    { zh: "支持", py: "zhī chí", th: "สนับสนุน", type: "verb" },
  ],

  hsk5: [
    { zh: "显著", py: "xiǎn zhù", th: "เด่นชัด", type: "adj" },
    { zh: "缓解", py: "huǎn jiě", th: "บรรเทา", type: "verb" },
    { zh: "谨慎", py: "jǐn shèn", th: "รอบคอบ", type: "adj" },
    { zh: "倾向", py: "qīng xiàng", th: "แนวโน้ม", type: "noun" },
    { zh: "启发", py: "qǐ fā", th: "แรงบันดาลใจ", type: "verb" },
    { zh: "效率", py: "xiào lǜ", th: "ประสิทธิภาพ", type: "noun" },
    { zh: "沟通", py: "gōu tōng", th: "สื่อสาร", type: "verb" },
    { zh: "观察", py: "guān chá", th: "สังเกต", type: "verb" },
    { zh: "理论", py: "lǐ lùn", th: "ทฤษฎี", type: "noun" },
    { zh: "方案", py: "fāng àn", th: "แผนงาน", type: "noun" },

    { zh: "分析", py: "fēn xī", th: "วิเคราะห์", type: "verb" },
    { zh: "现象", py: "xiàn xiàng", th: "ปรากฏการณ์", type: "noun" },
    { zh: "扩大", py: "kuò dà", th: "ขยาย", type: "verb" },
    { zh: "趋势", py: "qū shì", th: "แนวโน้ม", type: "noun" },
    { zh: "措施", py: "cuò shī", th: "มาตรการ", type: "noun" },
    { zh: "资源", py: "zī yuán", th: "ทรัพยากร", type: "noun" },
    { zh: "价值", py: "jià zhí", th: "คุณค่า", type: "noun" },
    { zh: "形成", py: "xíng chéng", th: "ก่อให้เกิด", type: "verb" },
    { zh: "坚持", py: "jiān chí", th: "ยืนหยัด", type: "verb" },
    { zh: "实施", py: "shí shī", th: "ดำเนินการ", type: "verb" },

    { zh: "创新", py: "chuàng xīn", th: "นวัตกรรม", type: "noun" },
    { zh: "传统", py: "chuán tǒng", th: "ดั้งเดิม", type: "noun" },
    { zh: "领域", py: "lǐng yù", th: "สาขา", type: "noun" },
    { zh: "结构", py: "jié gòu", th: "โครงสร้าง", type: "noun" },
    { zh: "系统", py: "xì tǒng", th: "ระบบ", type: "noun" },
    { zh: "管理", py: "guǎn lǐ", th: "บริหาร", type: "verb" },
    { zh: "组织", py: "zǔ zhī", th: "องค์กร", type: "verb" },
    { zh: "制定", py: "zhì dìng", th: "กำหนด", type: "verb" },
    { zh: "目标", py: "mù biāo", th: "เป้าหมาย", type: "noun" },
    { zh: "责任", py: "zé rèn", th: "ความรับผิดชอบ", type: "noun" },

    { zh: "环境", py: "huán jìng", th: "สิ่งแวดล้อม", type: "noun" },
    { zh: "社会", py: "shè huì", th: "สังคม", type: "noun" },
    { zh: "文化", py: "wén huà", th: "วัฒนธรรม", type: "noun" },
    { zh: "教育", py: "jiào yù", th: "การศึกษา", type: "noun" },
    { zh: "经济", py: "jīng jì", th: "เศรษฐกิจ", type: "noun" },
    { zh: "技术", py: "jì shù", th: "เทคโนโลยี", type: "noun" },
    { zh: "发展", py: "fā zhǎn", th: "พัฒนา", type: "verb" },
    { zh: "国际", py: "guó jì", th: "นานาชาติ", type: "noun" },
    { zh: "竞争", py: "jìng zhēng", th: "แข่งขัน", type: "verb" },
    { zh: "合作", py: "hé zuò", th: "ร่วมมือ", type: "verb" },

    { zh: "调查", py: "diào chá", th: "สำรวจ", type: "verb" },
    { zh: "研究", py: "yán jiū", th: "วิจัย", type: "verb" },
    { zh: "证明", py: "zhèng míng", th: "พิสูจน์", type: "verb" },
    { zh: "判断", py: "pàn duàn", th: "ตัดสิน", type: "verb" },
    { zh: "解释", py: "jiě shì", th: "อธิบาย", type: "verb" },
    { zh: "说明", py: "shuō míng", th: "ชี้แจง", type: "verb" },
    { zh: "解决", py: "jiě jué", th: "แก้ไข", type: "verb" },
    { zh: "调整", py: "tiáo zhěng", th: "ปรับ", type: "verb" },
    { zh: "提高", py: "tí gāo", th: "ยกระดับ", type: "verb" },
    { zh: "减少", py: "jiǎn shǎo", th: "ลดลง", type: "verb" },

    { zh: "增加", py: "zēng jiā", th: "เพิ่มขึ้น", type: "verb" },
    { zh: "保持", py: "bǎo chí", th: "รักษา", type: "verb" },
    { zh: "影响", py: "yǐng xiǎng", th: "ส่งผล", type: "verb" },
    { zh: "改变", py: "gǎi biàn", th: "เปลี่ยน", type: "verb" },
    { zh: "适应", py: "shì yìng", th: "ปรับตัว", type: "verb" },
    { zh: "接受", py: "jiē shòu", th: "ยอมรับ", type: "verb" },
    { zh: "拒绝", py: "jù jué", th: "ปฏิเสธ", type: "verb" },
    { zh: "选择", py: "xuǎn zé", th: "เลือก", type: "verb" },
    { zh: "机会", py: "jī huì", th: "โอกาส", type: "noun" },
    { zh: "挑战", py: "tiǎo zhàn", th: "ความท้าทาย", type: "noun" },

    { zh: "经验", py: "jīng yàn", th: "ประสบการณ์", type: "noun" },
    { zh: "能力", py: "néng lì", th: "ความสามารถ", type: "noun" },
    { zh: "知识", py: "zhī shi", th: "ความรู้", type: "noun" },
    { zh: "水平", py: "shuǐ píng", th: "ระดับ", type: "noun" },
    { zh: "表现", py: "biǎo xiàn", th: "ผลงาน", type: "noun" },
    { zh: "成果", py: "chéng guǒ", th: "ผลสำเร็จ", type: "noun" },
    { zh: "质量", py: "zhì liàng", th: "คุณภาพ", type: "noun" },
    { zh: "效果", py: "xiào guǒ", th: "ผลลัพธ์", type: "noun" },
    { zh: "优势", py: "yōu shì", th: "ข้อได้เปรียบ", type: "noun" },
    { zh: "缺点", py: "quē diǎn", th: "ข้อเสีย", type: "noun" },
  ],
};
